import { Download, Eye, Folder, Pencil, Trash2 } from 'lucide-react';
import { Button } from '@/shared/components/ui/button';
import type { CloudFile, Directory } from '../../types';
import { IconRegistry } from '../../registry/icon-registry';
import { canPreview, formatSize, getFileType } from '../../utils/file-utils';

interface Props { folders: Directory[]; files: CloudFile[]; selected: Set<string>; onSelect: (key: string, selected: boolean) => void; onFolder: (folder: Directory) => void; onPreview: (file: CloudFile) => void; onDownload: (file: CloudFile) => void; onRename: (item: Directory | CloudFile, type: 'folder' | 'file') => void; onDelete: (item: Directory | CloudFile, type: 'folder' | 'file') => void; }
const RowActions = ({ preview, download, rename, remove }: { preview?: () => void; download?: () => void; rename?: () => void; remove: () => void }) => <div className="flex justify-end gap-1">{preview && <Button size="icon-sm" variant="ghost" onClick={preview}><Eye className="size-4" /></Button>}{download && <Button size="icon-sm" variant="ghost" onClick={download}><Download className="size-4" /></Button>}{rename && <Button size="icon-sm" variant="ghost" onClick={rename}><Pencil className="size-4" /></Button>}<Button size="icon-sm" variant="ghost" className="text-destructive" onClick={remove}><Trash2 className="size-4" /></Button></div>;
export function ExplorerList({ folders, files, selected, onSelect, onFolder, onPreview, onDownload, onRename, onDelete }: Props) {
  return <div className="overflow-hidden rounded-xl border bg-card"><div className="hidden grid-cols-[32px_minmax(0,1fr)_100px_120px_150px] gap-3 border-b bg-muted/50 px-3 py-2 text-xs text-muted-foreground md:grid"><span /><span>الاسم</span><span>النوع</span><span>الحجم</span><span /></div>
    {folders.map((folder) => <div key={`folder-${folder.id}`} className="grid grid-cols-[32px_minmax(0,1fr)_auto] items-center gap-3 border-b px-3 py-2 last:border-0 md:grid-cols-[32px_minmax(0,1fr)_100px_120px_150px]"><input type="checkbox" checked={selected.has(`folder:${folder.id}`)} onChange={(e) => onSelect(`folder:${folder.id}`, e.target.checked)} /><button className="flex min-w-0 items-center gap-3 text-start" onClick={() => onFolder(folder)}><Folder className="size-7 shrink-0 text-primary" /><span className="truncate text-sm font-medium">{folder.dir_name}</span></button><span className="hidden text-xs text-muted-foreground md:block">مجلد</span><span className="hidden text-xs text-muted-foreground md:block">—</span><RowActions rename={() => onRename(folder, 'folder')} remove={() => onDelete(folder, 'folder')} /></div>)}
    {files.map((file) => { const config = IconRegistry[getFileType(file)]; const Icon = config.icon; return <div key={`file-${file.id}`} className="grid grid-cols-[32px_minmax(0,1fr)_auto] items-center gap-3 border-b px-3 py-2 last:border-0 md:grid-cols-[32px_minmax(0,1fr)_100px_120px_150px]"><input type="checkbox" checked={selected.has(`file:${file.id}`)} onChange={(e) => onSelect(`file:${file.id}`, e.target.checked)} /><button className="flex min-w-0 items-center gap-3 text-start" onClick={() => canPreview(file) && onPreview(file)}><span className={`rounded-md p-2 ${config.bg}`}><Icon className={`size-5 ${config.color}`} /></span><span className="truncate text-sm font-medium">{file.file_name}</span></button><span className="hidden truncate text-xs text-muted-foreground md:block">{file.extension?.toUpperCase()}</span><span className="hidden text-xs text-muted-foreground md:block">{formatSize(file.size)}</span><RowActions preview={canPreview(file) ? () => onPreview(file) : undefined} download={() => onDownload(file)} remove={() => onDelete(file, 'file')} /></div>; })}
  </div>;
}
